import java.io.IOException;


/**
 * @author andersonhicher
 *
 */


public class MenuInicial {

	public static void main(String[] args) {
		Paciente teste = new Paciente("Snow", "Masculino", "Akita", 30, 1, "13113319641", "16/11/2019");
		/*
		//Teste de cadastro:
		try {
			System.out.println("Entrou no cadastro:");
			teste.cadastroPaciente(teste);
		} catch (Exception e) {
			System.out.println("Falha ao entrar no cadastro: ");
			System.out.println(e.getMessage());
		}
		
		
		//Teste de listagem de pacientes:
		try {
			System.out.println("Entrou no método de listagem:");
			teste.listarPacientes();
		} catch (Exception e) {
			System.out.println("Falha ao listar ");
			System.out.println(e.getMessage());
		}
			
			
		//Teste de busca:
		try {
			System.out.println("Entrou na busca:");
			teste.buscaId(0);
		} catch (Exception e) {
			System.out.println("Falha ao entrar na busca: ");
			System.out.println(e.getMessage());
		}
			
		//Teste de edição:
		try {
			System.out.println("Entrou na edição:");
			teste.editarPacienteCadastrado(0, "kira", "feminino", "Fila", 60, 3, "35930926620", "16/11/2018");
		} catch (Exception e) {
			System.out.println("Falha ao entrar na edição: ");
			System.out.println(e.getMessage());
		}
		
		//Teste de exclusão:
		try {
			System.out.println("Entrou na exclusão:");
			teste.excluirPacienteCadastrado(1);
		} catch (Exception e) {
			System.out.println("Falha ao entrar na exclusão: ");
			System.out.println(e.getMessage());
		}
		
		
		*/
	} 

}
